localfile: graph.json
tempfile: .graph.temp

# lncli_path: output of `which lncli`
lncli_path: /usr/local/bin/lncli


# json_archive - a folder of timestamped graph json snapshots
# Make sure to .gitignore it
json_archive: archive

# everything below this is only used by snapshot.py
# you dont need to change it unless using the --remote-write flag
remote_host: user@example.com
remote_file: /some/path/on/remote/host
